baseURL = "https://example.com"
languageCode = "en-us"
title = "Vanilla"
theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-123456789-1"

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    pre = "edit"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    pre = "smile"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    pre = "rss"
    url = "/index.xml"
    weight = 5

[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Welcome to the Vanilla theme demo. Have a look around. Maybe even eat some ice cream."
  footerText = "Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
  hideFooter = false